import { Hono } from "hono";
import { cors } from "hono/cors";
import { ingestRoute } from "./routes/ingest";
import { sessionsRoute } from "./routes/sessions";
import { healthRoute } from "./routes/health";
import { SessionHub } from "./do/SessionHub";
import type { Env } from "./types";

export { SessionHub };

// @ts-ignore - generated by recorder build
let RJS_CONTENT = "// Recorder not built yet. Run: npm run build --workspace=recorder";
try {
  const mod = await import("./generated/r.js");
  RJS_CONTENT = mod.RJS_CONTENT;
} catch {}

const app = new Hono<{ Bindings: Env }>();

// CORS for dashboard
app.use(
  "/api/*",
  cors({
    origin: ["http://localhost:5173", "http://127.0.0.1:5173", "https://replay.yourdomain.com"],
    credentials: true,
  })
);

// Serve recorder script
app.get("/r.js", (c) => {
  return c.text(RJS_CONTENT, 200, {
    "Content-Type": "application/javascript",
    "Cache-Control": "public, max-age=3600",
    "Access-Control-Allow-Origin": "*",
  });
});

// API routes
app.route("/api/health", healthRoute);
app.route("/api/ingest", ingestRoute);
app.route("/api/sessions", sessionsRoute);

// Single session data
app.get("/api/session/:id", async (c) => {
  const id = c.req.param("id");
  const hub = c.env.SESSION_HUB.get(c.env.SESSION_HUB.idFromName("main"));
  return hub.fetch(new Request(`https://internal/session/${id}`));
});

// WebSocket upgrade for recorder
app.get("/ws/record", async (c) => {
  const hub = c.env.SESSION_HUB.get(c.env.SESSION_HUB.idFromName("main"));
  return hub.fetch(c.req.raw);
});

// WebSocket upgrade for dashboard live view
app.get("/ws/watch", async (c) => {
  const hub = c.env.SESSION_HUB.get(c.env.SESSION_HUB.idFromName("main"));
  return hub.fetch(c.req.raw);
});

export default {
  fetch: app.fetch,
};
