import { build } from "esbuild";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { dirname } from "path";

const outfile = "../worker/src/generated/r.js";

// Ensure output directory exists
const outDir = dirname(outfile);
if (!existsSync(outDir)) {
  mkdirSync(outDir, { recursive: true });
}

await build({
  entryPoints: ["src/index.ts"],
  bundle: true,
  minify: true,
  outfile,
  format: "iife",
  target: "es2020",
});

// Read the built file and export as a constant
const content = readFileSync(outfile, "utf-8");
const exportFile = outfile.replace(".js", ".ts");
writeFileSync(
  exportFile,
  `// Auto-generated by recorder build — do not edit manually\nexport const RJS_CONTENT = ${JSON.stringify(content)};\n`
);

console.log("Recorder built successfully:", outfile);
console.log("Export file:", exportFile);
